# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "fix**", "feature**", "develop**" ]
  pull_request:
    branches: [ "main", "fix**", "feature**", "develop**" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # - name: Test
    #   run: go test -v ./...
